### PR TITLE
Shopify provider fixes

### PR DESCRIPTION
**Pull request by cond0r**
- fixed Shopify types issues marked as TODO
- fixed the page query by id
- fixed GraphQL query deprecations
- changed error handling to display Shopify user errors
- removed unnecessary files

### CODE REVIEW

**Comment by vercel-team** [comment]
#### 📝Changed routes:


| [**/\[...pages\]**](https://commerce-h3ij33p4i.vercel.sh/[...pages]) | [**/search**](https://commerce-h3ij33p4i.vercel.sh/search) |
|:-:|:-:|
|<a href="https://commerce-h3ij33p4i.vercel.sh/[...pages]">Screenshot of /[...pages]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/WRegG7WgOhQg3uaa3yEOFWqCz3Y_.png">(view full size)</a> |<a href="https://commerce-h3ij33p4i.vercel.sh/search">Screenshot of /search</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/JRYXoskTmJS3qlGmtvKq34pMlR8_.png">(view full size)</a> |







Commit 0c2c7343c3163734b2258c33b7cd1842f6882690 (https://commerce-h3ij33p4i.vercel.sh).

**Review by devmiro — COMMENTED** [review]
Is it expected that when user click in search > clothes | shoes it doesn't find any matches and clear product list?
On master it seems to keep product list.

**Comment by cond0r** [comment]
As you can see on my test site https://commerce-git-shopify-cond0r.vercel.app it works when you click clothes, accessories or shoes. The search uses product type, product title or tags.

**Comment by devmiro** [comment]
> As you can see on my test site https://commerce-git-shopify-cond0r.vercel.app it works when you click clothes, accessories or shoes. The search uses product type, product title or tags.

Yes it works, I was testing the preview of Vercel bot creates.

**Review by okbel — APPROVED** [review]

**Comment by okbel** [comment]
Wonderful. Thank you @cond0r !

**Pull request merged**
