### PR TITLE
pumped next JS and other dependencies to latest version

### PR DESCRIPTION
**Pull request by ahmed-adly-khalil**
# version update for Next 12 + other NPM dependencies

- updated nextJS to v 12.0.1
- has to change LoginView.tsx and SignUpView.tsx as swc didn't like catch param destructuring and throw an error `failed to process not implemented: regenerator: complex pattern in catch clause`  
- updated yarn.lock

### CODE REVIEW

**Comment by luisorbaiceta** [comment]
This issue is solved in version 12.0.3

**Comment by ahmed-adly-khalil** [comment]
> This issue is solved in version 12.0.3

Sorry, can you clarify what issue?

**Comment by luisorbaiceta** [comment]
Param destructuring in catch clauses

**Comment by ahmed-adly-khalil** [comment]
> Param destructuring in catch clauses

That's nice, will update the PR 👌

**Comment by goncy** [comment]
@ahmed-adly-khalil thanks for this PR! But a similar one was merged https://github.com/vercel/commerce/pull/562 with some changes related to the package manager, hope to have more PRs in the future 🙌

**Pull request closed without merging**
