### PR TITLE
issue#1123 fix

### PR DESCRIPTION
**Pull request by sellimenes**
Issue #1123 , added Suspense to show loading skeleton on every single search request.

### CODE REVIEW

**Comment by leerob** [comment]
I'm not sure if this is necessary, it already feels really fast when going between searches to me. What do you see?

**Comment by sellimenes** [comment]
> I'm not sure if this is necessary, it already feels really fast when going between searches to me. What do you see?

When I try on slow internet, it doesn't feel juicy enough I think. With Suspense, it just 'feels' better

**Comment by muco-rolle** [comment]
I have a similar issue on my project, where it takes 1 to 2 seconds before the search parameter is added to the address bar.

**Comment by sellimenes** [comment]
> I have a similar issue on my project, where it takes 1 to 2 seconds before the search parameter is added to the address bar.

Can you also please try to use Suspense and share your experiences?

**Comment by leerob** [comment]
We'll likely move to this pattern: https://buildui.com/posts/instant-search-params-with-react-server-components

**Pull request closed without merging**
