### PR TITLE
Updated Saleor Provider

### PR DESCRIPTION
**Pull request by zaiste**
This PR supersedes the #277 It also incorporates the changes introduced by #252 Overall, this PR provides a minimal working example showing how to integrate Saleor with the Next.js Commerce platform. 

cc @patrys @okbel 

Additionally, I've updated a couple of dependencies (`package.json`) - leaving Next.js at `10.0.9-canary.5` because of issues that prevent images to be properly displayed cc @lfades

### CODE REVIEW

**Comment by lfades** [comment]
@zaiste What's the issue that prevents us from being on the latest Next.js version? 10.0.9 is quite behind

**Comment by zaiste** [comment]
@lfades Images didn't appear in `production` for any version of Next.js after the current one if I recall correctly. I can investigate further as I'd also prefer to be on the latest Next.js version here.

**Comment by lfades** [comment]
@zaiste Is that the case for the other providers? 🤔

**Comment by zaiste** [comment]
@lfades I haven't yet checked other providers. For clarity, currently, in this repository on the `master` branch, you use this older Next.js version i.e. `10.0.9-canary.5` ([ref](https://github.com/vercel/commerce/blob/master/package.json#L37)). In this PR, I decided to leave the Next.js version __unchanged__. We could address the Next.js upgrade in the following PR to make sure it works correctly for all providers across the board.

**Pull request merged**
