### PR TITLE
Shopify-remove-shopify-buy-package

### PR DESCRIPTION
**Pull request by LarsBuur**
his removes the final pieces of the obsolete shopify-buy package and the ENV´s it required.

### CODE REVIEW

**Comment by vercel-team** [comment]
#### 📝Changed routes:


| [**/cart**](https://commerce-6x54zak12.vercel.sh/cart) | [**/wishlist**](https://commerce-6x54zak12.vercel.sh/wishlist) |
|:-:|:-:|
|<a href="https://commerce-6x54zak12.vercel.sh/cart">Screenshot of /cart</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/WSlsE_hAr_FOgsVy1NUmGAfnYWQ_.png">(view full size)</a> |<a href="https://commerce-6x54zak12.vercel.sh/wishlist">Screenshot of /wishlist</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/5VaVyZqoM3w4Ytr4RFW3kZb_VJE_.png">(view full size)</a> |







Commit 1767e5ff9c002deb5e52aa5ad32a53317f5c8d90 (https://commerce-6x54zak12.vercel.sh).

**Comment by okbel** [comment]
_checking_ 👀

**Comment by okbel** [comment]
Let's merge it after we merge `agnostic`

**Comment by okbel** [comment]
We updated it recently! Thank you!

**Pull request closed without merging**
