### PR TITLE
Feat/vendure checkout

### PR DESCRIPTION
**Pull request by michaelbromley**
Cleaned up a few issues from @hangai247's work so far in #714 

Namely:

- Add missing `graphql` dependency to the vendure packages so that codegen works
- Run codegen because a needed generated type was missing
- Add `customCheckout: true` to the commerce.config.json file
- Make sure to assign a Customer to the order during checkout.
- Clean up a few errors here and there.

### CODE REVIEW

**Comment by briandiaz** [comment]
Hey when will this be merged?

**Comment by cond0r** [comment]
@michaelbromley Hello, this PR contains type errors, so preview deployment could not go through.

Screen Shot 2022-08-11 at 2 28 02 PM

**Comment by PicchiKevin** [comment]
Quickly ran this, no apparent bugs. Can you please review this @lfades?

**Comment by dnk8n** [comment]
What's the status of this? Are we able to use Vendure with Next.js Commerce?

**Comment by GamfaleanuVlad** [comment]
Heyo, is this branch usable? I would kinda need this in the near future and I don't really care if it is on the main branch or anything.

**Comment by michaelbromley** [comment]
@GamfaleanuVlad as far as I know, yes. But since this branch is pretty old now, you might need to merge the latest updates from `main` and potentially handle any conflicts or changes. Hopefully there won't be too many.

**Comment by leerob** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966

Happy to talk about the Vendure version of v2!

**Pull request closed without merging**
