### PR TITLE
Optimistic cart

### PR DESCRIPTION
**Pull request by leerob**
Switch to `useOptimistic` for instant feedback on cart +/-. You'll notice that the Server Actions run serially to ensure that all write mutations succeed. If you try to navigate to checkout, it kicks off an action to redirect. If the other mutations have not yet completed, it will be queued behind those and wait for all mutations to settle. This ensures you can't navigate to the cart while cart additions or subtractions are happening.

### CODE REVIEW

**Comment by michael-land** [comment]
@leerob  It looks like this didn't work as expected when the item is taxable. The optimisticUpdate shows incorrect tax and total

**Comment by leerob** [comment]
I don't believe any of the items in this demo have tax set up - could you share a video?

**Comment by michael-land** [comment]
From this video, you can see that the total and tax values do not match between the calculated value and the API response

https://github.com/user-attachments/assets/2682e9cb-7a81-4ca9-acf6-b43aa6cfa214

**Comment by leerob** [comment]
Oh, okay! Yeah, this isn't implemented here because we aren't using tax on the items. Happy to accept upstream PRs for solutions here. 

https://github.com/vercel/commerce/pull/1365

**Comment by michael-land** [comment]
I don't believe this is possible with the Storefront API, as Shopify does not expose tax rate information. One way to work around this is to display the subtotal instead of the total, and for the tax rate, just say 'calculated at checkout'.

**Pull request merged**
