### PR TITLE
Button and I18n Widget Fix

### PR DESCRIPTION
**Pull request by Regaron**
Fixed Button component missing onClick prop and I18n widget image being outside button also the usernav item not showing when cart is empty

### CODE REVIEW

**Comment by luke-denton-aligent** [comment]
@Regaron Thanks for bringing this functionality back in! I wonder if we can also update the Button component to fix the Proceed to Checkout "button"? That element is actually an `<a>`, however uses `Button.tsx` to render, which means clicking on it also does nothing

**Comment by okbel** [comment]
Screen Shot 2020-12-02 at 11 18 55 AM

I can still see the issue

**Comment by Regaron** [comment]
It’s showing correctly in latest preview:
https://commerce-e57urrj2r.vercel.app/

**Comment by okbel** [comment]
Had to close it because it has been solved already. Thank you!!

**Comment by luke-denton-aligent** [comment]
Hi @okbel, I'm curious why this was closed. If we look at the Button.tsx component in the `master` branch, the `onClick` prop still isn't handled. This means that anyone who is starting a new project from the current head of master will get buttons that don't work :confused:

**Pull request closed without merging**
