### PR TITLE
Shopify Provider

### PR DESCRIPTION
**Pull request by petermekhaeil**
Opening this Pull Request to welcome the community to help out.

**Status**

- [x] CommerceProvider
- [x] API Operations - Get all collections
- [x] API Operations - Get all pages
- [x] API Operations - Get all product paths
- [x] API Operations - Get all products
- [ ] API Operations - Get page
- [x] API Operations - Get product
- [ ] API Operations - Get Site Info
- [x] Hook - Add Item
- [x] Hook - Remove Item
- [x] Hook - Update Item
- [ ] Hook - Get Cart
- [ ] Auth and customer information
- [ ] Product Options - Size, Colours
- [ ] Read Currency Code from Shopify API
- [ ] Redirect `/checkout` to Shopify checkout page.
- [ ] Remove dependency on `shopify-js-buy` (big rock item).
- [ ] Typing
- [ ] Tests

**Getting Started**

1. Install dependencies (until the dependency on `shopify-buy` has been removed)

```
yarn install shopify-buy
yarn install -D @types/shopify-buy
```

3. Environment variables need to be set:

```
SHOPIFY_STORE_DOMAIN=
SHOPIFY_STOREFRONT_ACCESS_TOKEN=
NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN=
NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN=
```

4. Point the framework to `shopify` by updating `tsconfig.json`:

```
"@framework/*": ["framework/shopify/*"],
"@framework": ["framework/shopify"]
```

**Modifications required to app**

- `ProductView` needs a modification to allow products to be added to the cart (existing codebase is casting to Number and Shopify uses strings).

```js
// components/product/ProductView/ProductView.tsx
const ProductView: FC<Props> = ({ product }) => {
  const addToCart = async () => {
    setLoading(true)
    try {
      await addItem({
        productId: product.id,
        variantId: variant ? variant.id : product.variants[0].id,
      })
      openSidebar()
      setLoading(false)
    } catch (err) {
      setLoading(false)
    }
  }
}
```

- `CartSidebarView` needs a modification to proceed to checkout (Shopify provides its own checkout page).

```js
// components/cart/CartSidebarView/CartSidebarView.tsx
import { useCommerce } from '@framework'

const CartSidebarView: FC = () => {
  const { checkout } = useCommerce()
  return (
    <Button href={checkout.webUrl} Component="a" width="100%">
      Proceed to Checkout
    </Button>
  )
}
```

### CODE REVIEW

**Comment by LarsBuur** [comment]
I have the code running in plain node with my shopify store data and can see a frontpage and a product-detail page.
The list of pages is rendered.
Typescript reports 53 errors. 

The details about ProductView CartSidebarView are not clear to me. Should I replace the contents of these files with the details from the README?

Looking into the code it seems that we use two methods to fetch data from shopify (Shopify GraphQL endpoint and the npm shopify-js-buy). It seems that there is a rather big chunk of work converting all calls into GraphQL. 

I have been looking for a good place to start helping out but the path is not clear to me. 

Especially the mapping of the GraphQL data into the commerce data format is not clear.

Maybe framework/shopify/utils/types.ts exist in your local environment ? (Page, PageEdge) is defined in get-all-pages.ts but the file does not exist. Another maybe the file is autogenerated and I am missing a step?

**Comment by petermekhaeil** [comment]
Thanks for that. I didn't realised I moved a file and didn't update the references. I've updated the PR.

The modifications for `ProductView` is to replace the `addToCart` function with the sample I have given. Likewise for `CartSidebarView` the URL for "Proceed to checkout" needs to be updated.

(Do note though, I see these modifications as temporarily until the commerce framework can support such features without the user having to modify the UI)

And yes, converting `shopify-buy` to bare graphql calls is a big rock to take on. Will need the communities help with this. I think taking on everything else and getting the provider to a stable position is priority over removing the dependency.

**Comment by LarsBuur** [comment]
I will dig into this and focus on feature completion before GraphQL

**Comment by cond0r** [comment]
Here you can find my attempt with Shopify Storefront API (without shopify-js-buy)
https://github.com/cond0r/commerce/tree/agnostic

Live Demo:
https://commerce-e5ghtrr6z.vercel.app/

After i will implement missing stuff i need for my personal project and there will not be another pull request with this provider, i will try a pull request myself.

**Comment by okbel** [comment]
We will continue from now on! Thank you @petermekhaeil !!

**Comment by TommySorensen** [comment]
@okbel Any plans on when you release the Shopify provider you are working on? I am about to start a shopify shop with NextJS but i don't want start on something you might be release soon 🙂

**Comment by okbel** [comment]
@TommySorensen Yes! The release will be most likely next week! We finished the FeaturesAPI, check the agnostic branch!! I'm about to merge a lot of func from shopify

**Comment by rodrigoehlers** [comment]
@okbel I see the agnostic branch was merged, does this mean the Shopify integration is complete? If not, where can I help?

**Pull request merged**
