### PR TITLE
replace deprecated uuidv4 by uuid

### PR DESCRIPTION
**Pull request by Florian-crg**
`DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.`

>This module will be deprecated in the future in favour of module uuid. Most of the functionality of this module is already >included in uuid since version 8.3.0, so most of the functions of this module have already been marked as deprecated.

https://github.com/thenativeweb/uuidv4#please-note

### CODE REVIEW

**Comment by goncy** [comment]
@Florian-crg this has conflicts and modifies the entire lock files, can you update those to just change the related dependencies? Thanks!

**Comment by Florian-crg** [comment]
@goncy  I removed the lock files from the MR.

**Review by goncy — APPROVED** [review]

**Comment by goncy** [comment]
@Florian-crg  Build is failing for bigcommerce

**Review by goncy — CHANGES_REQUESTED** [review]
Build is broken

**Comment by goncy** [comment]
@Florian-crg I will close this to avoid conflicts on it, feel free to reopen in the future if continued!

**Pull request closed without merging**
