### PR TITLE
feat: add a basic product ld schema on product details page

### LINKED ISSUE #1012: Add JSON-LD metadata for products
https://nextjs.org/docs/app/building-your-application/optimizing/metadata#json-ld

### PR DESCRIPTION
**Pull request by abhu-A-J**
closes #1012 

- [x] Add a product json ld schema on products details page

Hey @leerob , first time contributor to project here, thought the issue was straight forward, so decided to raise a PR for it. 
Added the schema with basic details.

Kindly let me know if any more information needs to be added to the schema! Looking forward to playing around with more issues mentioned!

### CODE REVIEW

**Comment by manovotny** [comment]
@abhu-A-J thanks for contributing! Awesome start! According to the [validator](https://search.google.com/test/rich-results) though...

> Either "offers", "review", or "aggregateRating" should be specified

https://search.google.com/test/rich-results/result/r%2Fproduct?id=gE7_Kb4IkbD49Xz3TiX09w

Think you could get one of those added? `offers` would probably be easiest.

**Comment by abhu-A-J** [comment]
> @abhu-A-J thanks for contributing! Awesome start! According to the [validator](https://search.google.com/test/rich-results) though...
> 
> > Either "offers", "review", or "aggregateRating" should be specified
> 
> https://search.google.com/test/rich-results/result/r%2Fproduct?id=gE7_Kb4IkbD49Xz3TiX09w
> 
> Think you could get one of those added? `offers` would probably be easiest.

Hi @manovotny missed that. 😓  
Yes, I can add that as well. 

Looking around the response given I think this can be done?

```ts
  const productJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: product.title,
    description: product.description,
    image: product.featuredImage.url,
    offers: {
      '@type': 'AggregateOffer',
      availability: product.availableForSale
        ? 'https://schema.org/InStock'
        : 'https://schema.org/OutOfStock',
      priceCurrency: product.priceRange.minVariantPrice.currencyCode,
      highPrice: product.priceRange.maxVariantPrice.amount,
      lowPrice: product.priceRange.minVariantPrice.amount
    }
  };
```

Which should generate ld which should get rid of the error. It still misses an optional field called `offerCount`, have a suggestion to infer that field? 
```
<script type="application/ld+json">

{
	"@context": "https://schema.org",
	"@type": "Product",
	"name": "Acme T-Shirt",
	"description": "60% combed ringspun cotton/40% polyester jersey tee.",
	"image": "https://cdn.shopify.com/s/files/1/0754/3727/7491/products/t-shirt-color-beige.png?v=1682089385",
	"offers": {
		"@type": "AggregateOffer",
		"availability": "http://schema.org/InStock",
		"priceCurrency": "USD",
		"highPrice": "1495",
		"lowPrice": "1250"
	}
}

</script>

```

Seems like offers can take multiple shapes. Would this be alright for this case. Let me know if you if I missed something or something extra I need to add and I'll update the PR. Thanks!

**Comment by manovotny** [comment]
@abhu-A-J I think that looks great. Go for it. If I can make one more ask, could you also look into adding the [schema-dts](https://www.npmjs.com/package/schema-dts) package as the [Next.js Docs outline](https://nextjs.org/docs/app/building-your-application/optimizing/metadata#json-ld)? I wonder if it would have caught this as a required prop.

**Comment by abhu-A-J** [comment]
> @abhu-A-J I think that looks great. Go for it. If I can make one more ask? Could you also look into adding the [schema-dts](https://www.npmjs.com/package/schema-dts) package as the [Next.js Docs outline](https://nextjs.org/docs/app/building-your-application/optimizing/metadata#json-ld)? I wonder if it would have caught this as a required prop.

Yes off course! I did explore it out and I don't think the type helper are strict enough to catch errors like the one I did. IT does help out with getting possible properties which we can add but the type narrowing does not let know, if we are missing required fields.  Posting some sample below

**Usage I: No type error, but a invalid shape.**
```ts
  const schema: WithContext<Product> = {
    '@context': 'https://schema.org',
    '@type': 'Product',
  };
```

**Usage II : Type error, and a invalid shape.**
```ts
 const schema: WithContext<Product> = {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: 'Product Name',
    description: 'Product Description',
    image:
      'https://cdn.shopify.com/s/files/1/0754/3727/7491/products/t-shirt-color-beige.png?v=1682089385',
    offers: {},
  };
```
**Usage III : No Type Error, and a invalid shape.**
```ts
  const schema: WithContext<Product> = {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: 'Product Name',
    description: 'Product Description',
    image:
      'https://cdn.shopify.com/s/files/1/0754/3727/7491/products/t-shirt-color-beige.png?v=1682089385',
    offers: {
      '@type': 'AggregateOffer',
    },
  };


**I think since the LD Schema is used only on one page, it does not seem to add a lot of benefit if cannot get the errors during development process. But let me know your thoughts on this, I think it can be skipped**

**Comment by manovotny** [comment]
[Validation looks good now](https://search.google.com/test/rich-results/result/r%2Fproduct?id=oOO3UVWUOEYhCLT-OC1Jng)! Thanks for doing this, @abhu-A-J! 🖤

CleanShot 2023-05-22 at 12 02 48@2x

**Review by manovotny — APPROVED** [review]

**Pull request merged**
