### PR TITLE
vendure custom checkout support #619

### PR DESCRIPTION
**Pull request by hangai247**

### CODE REVIEW

**Comment by michaelbromley** [comment]
Relates to #619
@okbel FYI this was done in coordination with me in the Vendure slack. Soninkhangai has agreed to take on some maintenance of this integration 👍

**Comment by briandiaz** [comment]
Hey @michaelbromley 

Is there an ETA for this feature to be merged?

cc: @hangai247

**Comment by michaelbromley** [comment]
@briandiaz I don't know, I'm not a maintainer of this repo so I cannot decide that unfortunately 😢

**Comment by okbel** [comment]
@michaelbromley Do you have a PR done for this? Maybe I missed this. If `Soninkhangai` can collaborate on this we would be more than happy to merge and review it!

**Comment by okbel** [comment]
@hangai247 Could you please add a Description to the PR to understand all you're adding please? We can review it and merge it.

**Comment by okbel** [comment]
@michaelbromley Does this have your approval from the Vendure perspective? All approved practices?

**Comment by michaelbromley** [comment]
@okbel I'm just pulling this PR in locally to try it out. Unfortunately just had to spend ages trying to resolve https://github.com/vercel/commerce/issues/674 (in the end I used the suggested fix at https://github.com/vercel/commerce/issues/681#issuecomment-1041921734 to get it working). Will update this PR with my feedback.

**Comment by michaelbromley** [comment]
@okbel ok I ended up having to make a bunch of fixes. @hangai247's work on this PR is excellent, so it was mainly just polishing up a few things and handling some cases in the checkout flow that weren't already covered. This is in a new PR at #760.

**Comment by leerob** [comment]
Hey! Following up here. Is this something you're still interested in seeing through?

**Comment by michaelbromley** [comment]
Hi @leerob. I'd suggest this PR be closed in favour of #760.

**Pull request closed without merging**
