### PR TITLE
Prevent click-outside from losing children refs

### PR DESCRIPTION
**Pull request by luisorbaiceta**
This PR allows the ClickOutside component to have a direct children with a ref without It being lost when invoking the `React.Clone` method.

### CODE REVIEW

**Comment by okbel** [comment]
@luisorbaiceta Could you resolve the conflicts? Thank you for this! I'll take a look right after. 🙏

**Comment by luisorbaiceta** [comment]
Done!

**Review by dominiksipowicz — APPROVED** [review]

**Comment by dominiksipowicz** [comment]
@luisorbaiceta thank you ❤️

**Comment by luisorbaiceta** [comment]
> @luisorbaiceta thank you ❤️ 

My pleasure @dominiksipowicz

**Pull request merged**
